### ISSUE TITLE
[ion-concentration-biomodulator]: replace dip switch with push button

### ISSUE THREAD

**Issue by AydinGokce** [GeneralCybernetics/hardware#15]

**Comment by elijah0528** [comment]
![Uploading Screenshot 2024-08-14 at 3.40.41 PM.png…]()

**Comment by elijah0528** [comment]
<img width="483" alt="Screenshot 2024-08-14 at 3 41 02 PM" src="https://github.com/user-attachments/assets/7f14b2d4-0fef-4b80-9314-0e7b95674580">
